export const movies=[
        {
           id: 1,
           title:"The Avengers",
           plot:"Supernatural powers shown in the movie",
           poster:"https://www.themoviedb.org/t/p/original/pdhOE0NAZaPzjsgTvatRP1xFhG3.jpg",
           price:199,
           rating:8.0,
           stars:0,
           fav:false, 
           isIncart:false, 
        },
        {
            id:2,
            title:"The Dark Knight",
            plot:"When the menance known as the Joker wreaks havoc and chaos on the people of Gotham",
            poster:"https://www.themoviedb.org/t/p/original/pdhOE0NAZaPzjsgTvatRP1xFhG3.jpg", 
            price:299,
            rating:8.5,
            stars:0,
            fav:false, 
            isIncart:false, 
        },
        {
            id:3,
            title:"Iron Man",
            plot:"After being held captive in Afgan cave,billionare engineer Tony Stark creates ...",
            poster:"https://www.themoviedb.org/t/p/original/pdhOE0NAZaPzjsgTvatRP1xFhG3.jpg",
            price:399,
            rating:8.5,
            stars:0,
            fav:false, 
            isIncart:false, 
        },
]